import type {
  SourceContract,
  SourceRef,
} from '@co-kyo/skillpack-types';

export const refs = {
  run: { path: '{workDir}/.meta/run/run.json', description: '运行信封', required: true },
  anchors: { path: '{workDir}/.meta/brainstorm/anchors.json', description: '共享骨架', required: true },
  requirementWeb: { path: '{workDir}/.meta/requirement-web.json', description: '需求网', required: true },
  partitionAnalysis: { path: '{workDir}/.meta/partition-analysis.json', description: '分区分析', required: true },
  executionPlan: { path: '{workDir}/execution-plan.md', description: '执行计划', required: true },
  scanIndex: { path: '{workDir}/.meta/.raw-materials/index.json', description: '素材索引', required: true },
  scanMaterials: { path: '{workDir}/.meta/.raw-materials/*.md', description: '素材正文', required: true },
  capabilityGraph: { path: '{workDir}/.meta/capability-graph.json', description: '能力图谱', required: true },
  dependencyGraph: { path: '{workDir}/.meta/dependency-graph.json', description: '依赖图', required: true },
  highgrounds: { path: '{workDir}/.meta/highgrounds.json', description: '战略高地', required: true },
  learningPath: { path: '{workDir}/.meta/learning-path.json', description: '学习路径', required: true },
  evaluations: { path: '{workDir}/.meta/evaluations.json', description: '评估结果', required: true },
  readme: { path: '{workDir}/README.md', description: '命题总览', required: true },
  candidates: { path: '{workDir}/.meta/candidates.md', description: '候选池', required: true },
  researchPlan: { path: '{workDir}/.meta/research-plan.json', description: '能力研究素材分配与 usage trace', required: true },
  capabilities: { path: '{workDir}/capabilities/*.md', description: '能力主文件', required: true },
  summaries: { path: '{workDir}/.meta/summaries/*.json', description: '能力摘要', required: true },
  capabilitiesReadme: { path: '{workDir}/capabilities/README.md', description: '能力索引', required: true },
  briefing: { path: '{workDir}/.meta/briefings/{seq}-{short_name}.md', description: '命题 Briefing', required: true },
  overview: { path: '{workDir}/{seq}-{short_name}/overview.md', description: 'Overview', required: true },
  edgeCases: { path: '{workDir}/{seq}-{short_name}/edge-cases.md', description: 'Edge Cases', required: true },
  tradeoffs: { path: '{workDir}/{seq}-{short_name}/trade-offs.md', description: 'Trade-offs', required: true },
  references: { path: '{workDir}/{seq}-{short_name}/references.md', description: 'References', required: true },
  experiment: { path: '{workDir}/{seq}-{short_name}/experiment/README.md', description: 'Experiment', required: true },
  ladder: { path: '{workDir}/{seq}-{short_name}/learning-ladder.md', description: '学习阶梯', required: true },
  assemblyRatioTrace: { path: '{workDir}/{seq}-{short_name}/_assembly_ratio_trace.json', description: '组装特化占比 trace', required: true },
  schemasScan: { path: 'assets/03-scan/schemas.md', description: '扫描输出格式', required: true },
  refSources: { path: 'assets/common/ref-sources.md', description: 'T0 域名表 + 反爬域名表 + 信源分级规则', required: true },
  strategyLevel: { path: 'assets/common/strategy-level.md', description: '密度参数查表', required: true },
  protocolScheduling: { path: 'assets/common/protocol-scheduling.md', description: '子 agent 调度规则', required: true },
  pipelineParams: { path: 'assets/common/pipeline-params.md', description: '管线参数配置', required: true },
  subagentBudget: { path: 'assets/common/subagent-budget.md', description: '子 agent 窗口预算与输入压缩', required: true },
  antiCrawlFetch: { path: 'plugins/anti-crawl-fetch.md', description: 'Playwright 抓取', required: false },
  agentInit: { path: 'assets/01-brainstorm/agent-init.md', description: '维度 Agent 初始化定义', required: true },
  schedulingDetail: { path: 'assets/01-brainstorm/scheduling-detail.md', description: '调度参数与降级', required: true },
  barrierCheck: { path: 'assets/01-brainstorm/barrier-check.md', description: 'Barrier 检查项与决策矩阵', required: true },
  fallbackProtocol: { path: 'assets/01-brainstorm/fallback-protocol.md', description: '收敛者失败降级协议', required: true },
  brainstormSchemas: { path: 'assets/01-brainstorm/schemas.md', description: '头脑风暴输出格式', required: true },
  yearRules: { path: 'assets/00-intent-anchor/year-rules.md', description: '年限推断规则', required: true },
  skipRules: { path: 'assets/00-intent-anchor/skip-rules.md', description: '跳过判断规则', required: true },
  evaluationMethod: { path: 'assets/05-evaluate-pool/method.md', description: '评估方法论（投影）', required: true },
} satisfies Record<string, SourceRef>;

export const contracts: SourceContract[] = [
  { id: 'schemas-scan', kind: 'schema', path: 'assets/03-scan/schemas.md', description: '扫描输出格式' },
  { id: 'schemas-brainstorm', kind: 'schema', path: 'assets/01-brainstorm/schemas.md', description: '头脑风暴输出格式' },
  { id: 'ref-sources', kind: 'policy', path: 'assets/common/ref-sources.md', description: '信源分级与反爬域名' },
  { id: 'protocol-scheduling', kind: 'policy', path: 'assets/common/protocol-scheduling.md', description: '子 agent 调度规则' },
  { id: 'protocol-checkpoint', kind: 'policy', path: 'assets/common/protocol-checkpoint.md', description: '检查点协议' },
];
